name: CI

on:
  push:
    branches:
      - main
      - "001-*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2", "3.3", "3.4"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Ensure LaTeX engines and converters are available for integration specs
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            dvisvgm \
            pdf2svg \
            poppler-utils \
            imagemagick \
            ghostscript

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Run lint
        run: bundle exec standardrb

      - name: Run specs
        run: bundle exec rspec
